### ISSUE TITLE
Ability to not update disabled apps

### ISSUE THREAD

**Issue by rubikscraft** [GrapheneOS/Apps#126]
It would be great if there was an option to tell the updater to not update certain apps.
This is useful when you have disabled apps, because disabled apps get reenabled if you update them.

If there is a way to detect if an app is disabled, it would be even better if the updater could use that information to ignore disabled apps.

I for example prefer to use the google camera instead of the graphene one. So I disabled the graphene camera to keep it "bloat free". But now the app updater insists on updating the app, and therefore reenabling it.

**Comment by thestinger** [comment]
> I for example prefer to use the google camera instead of the graphene one. So I disabled the graphene camera to keep it "bloat free".

Worth noting as a side thing that this is broken because only the system camera app can provide the media capture intents used by other apps to ask you to take a picture or video on their behalf rather than implementing their own camera interface and requiring the camera (and possibly microphone) permissions.
