### ISSUE TITLE
Consider deprivileging Apps and allowlist in OS on it being a known source of installers

### ISSUE THREAD

**Issue by quh4gko8** [GrapheneOS/Apps#172]
Extend the toggle to automatically update installed apps to also prevent automatic installs on privileged context by showing a confirmation dialog beforehand

In privileged context, installing apps is done automatically, without any prompts from Package Installer.

**Comment by quh4gko8** [comment]
It'd may be desirable to not accidentally install apps once downloaded

**Comment by lberrymage** [comment]
I think this could be done without changing anything OS-wise or permission-wise by adding a toggle which controls the flag passed to `setRequireUserAction()` (either `USER_ACTION_NOT_REQUIRED` or `USER_ACTION_REQUIRED`).

**Comment by lberrymage** [comment]
What I mean is that you could optionally set `USER_ACTION_REQUIRED` instead of `USER_ACTION_NOT_REQUIRED` via a user-visible toggle. That way you can get the behavior you want (PackageInstaller prompts) even in a privileged context. There's no need to remove the privileged package management permissions.

**Comment by thestinger** [comment]
This is done to the extent possible while still supporting unattended updates for apps which are not currently installed by Apps.
