### ISSUE TITLE
Installing google services on a seperate profile on LineageOS

### ISSUE THREAD

**Issue by zachvlat** [GrapheneOS/Apps#240]
Yes, I know, this isn't meant to be installed on other OS's, other than Graphene, but I decided to give it a try and install it on LineageOS 19.1 without gapps or microg (my phone isn't pixel unfortunately). I created a seperate profile and install this app to get google services on a separate profile, but e.g. google maps didn't work and I 'm constantly getting the message to install google services. Does anyone know any extra dependencies I need in order to make it work? Thank you!

If this issue is out of the scope of this repo, just close it!

**Comment by thestinger** [comment]
Our app repository has mirrors of the official Google Play apps. It's not going to work unless you have GrapheneOS since the sophisticated sandboxed Google Play compatibility layer allowing those to work as regular sandboxed apps is part of the OS. The apps themselves in the repository are unmodified and installing them as regular apps won't work without the compatibility layer.
