### ISSUE TITLE
Ability to uninstall GrapheneOS apps.

### ISSUE THREAD

**Issue by jcperil** [GrapheneOS/Apps#272]

**Comment by thestinger** [comment]
The app repository client provides a link to the app settings in the Settings app where apps can be disabled.

**Comment by jcperil** [comment]
It's not the same thing as uninstalled. These are not system apps. I would like to control which apps to install in the userland. How do you address this issue?

**Comment by thestinger** [comment]
They are system apps. You can't remove components from the OS images because they're immutable and verified from a root of trust. Disabling apps prevents them from running. Disabling them is reversible since you can enable them again, It's a perfectly good way of handling this.

It is technically possible to mark system components as uninstalled in profiles but not via the normal user interface and it isn't a good idea. We recommend against using ADB on a production device, especially to do invasive, unsupported things like marking components uninstalled in profiles. They will still be considered installed as packages in the package registry. The only difference from disabling the app and marking it uninstalled in a profile is whether it still appears in settings and can have app data, but you can disable and clear app data in which case the only difference is whether it appears in settings. Do you really want to hide it in the Settings app badly enough to use developer tools?

**Comment by thestinger** [comment]
None of this is relevant to our app repository client.

**Comment by jcperil** [comment]
I do not understand why should a browser, or a camera app for instance be declared a system app in the first place.

**Comment by thestinger** [comment]
They aren't declared as a system app. System app means an app shipped as part of the OS.

**Comment by thestinger** [comment]
By the way, only camera apps included in the OS can implement the media capture intents since Android 11. If you disable all the system camera apps, apps using the media capture intents will break. Disabling the system camera app isn't something you should do. Disabling the browser is fine if you installed another browser implementing the standard intents.

**Comment by jcperil** [comment]
> They aren't declared as a system app. System app means an app shipped as part of the OS.

>> They are system apps. . You can't remove...

You are contradicting yourself. You just said that above.

Why do you have to make vanadium, auditor, camera etc. part of the immutable image?

> Disabling the system camera app isn't something you should do.

I have disabled the default camera app in other operating systems in the past and Open Camera app worked just fine. So, I don't know what you mean by that.

> Disabling the browser is fine...

Disabling is besides the point. I would like to exercise the freedom to uninstall any apps in the userspace.

**Comment by thestinger** [comment]
> You are contradicting yourself

No, you're misunderstanding. Being built into the OS is what makes them a system app. That's what it means. They aren't declared as one.

> Why do you have to make vanadium, auditor, camera etc. part of the immutable image?

The whole OS is verified from the root of trust. Factory reset wipes everything that's not.

There must be a system camera app and system browser. Only system camera apps can provide media capture intents. There must be a default system browser but it's fine to disable if you install another.

> I have disabled the default camera app in other operating systems in the past and Open Camera app worked just fine. So, I don't know what you mean by that.

Android 11 and later only allows system camera apps to provide the media capture intents. Apps using those won't work if you disable the system camera app(s).

> Disabling is besides the point. I would like to exercise the freedom to uninstall any apps in the userspace.

Disabling and uninstalling from a profile are nearly equivalent. If you insist on uninstalling from the profile, learn how to do it with ADB using the `pm` command. The only actual difference is you won't be able to see it in Settings to re-enable it and would instead have to reinstall it in the profile. Either way it's available in the OS images.
